name:      Jacudibu
author:    Jacudibu
email:     jacudibu@gmail.com


url:       "http://jacudibu.com"
permalink: /blog/:year/:month/:day/:title


excerpt_separator: <!--more-->

#pagination
paginate: 10
paginate_path: "blog/page:num"

gems:
  - jekyll-redirect-from